reference_path: tSFReference
test_path: G:\tS\ReviewHelper\CO20_Special_Activity_1A.MCN_Aliabad
review_directory_name: Review

tSF_config:
  config: dzn_tSFramework\dzn_tSFramework_Init.sqf
  path: dzn_tSFramework\Modules
  pattern: /tSF_module_([a-zA-Z]*)[\s=]+(false|true)/

Checklist:
  Core:
    - file: init.sqf
    - file: initServer.sqf
    - file: overview.jpg
      alert: true
    - file: description.ext
      alert: true
  Dynai:
    - file: dzn_dynai\Settings.sqf
    - file: dzn_dynai\Zones.sqf
      alert: true
  Gear:
    - file: dzn_gear\Settings.sqf
    - file: dzn_gear\Kits.sqf
      alert: true
    - file: dzn_gear\GearAssignementTable.sqf
      alert: true
  tSF:
    - file: dzn_tSFramework\dzn_tSFramework_Init.sqf
  tSF_modules:
    - file: _tSF_\IntroText\Settings.sqf
      alert: true
    - file: _tSF_\Briefing\Settings.sqf
    - file: _tSF_\Briefing\tSF_briefing.sqf
      alert: true
    - file: _tSF_\MissionConditions\Settings.sqf
      alert: true
    - file: _tSF_\Interactives\Settings.sqf
      alert: true
    - file: _tSF_\AirborneSupport\Settings.sqf
      alert: true
    - file: _tSF_\ArtillerySupport\Settings.sqf
      alert: true
    - file: _tSF_\EditorVehicleCrew\Settings.sqf
      alert: true
    - file: _tSF_\Conversations\Settings.sqf
    - file: _tSF_\tSNotes\Settings.sqf
    - file: _tSF_\tSSettings\Settings.sqf
    - file: _tSF_\MissionDefaults\Settings.sqf
    - file: _tSF_\JIPTeleport\Settings.sqf
    - file: _tSF_\CCP\Settings.sqf
    - file: _tSF_\FARP\Settings.sqf
    - file: _tSF_\Authorization\Settings.sqf
    - file: _tSF_\ACEActions\Settings.sqf
    - file: _tSF_\POM\Settings.sqf
    - file: _tSF_\EditorUnitBehavior\Settings.sqf
    - file: _tSF_\EditorRadioSettings\Settings.sqf
    - file: _tSF_\tSAdminTools\Settings.sqf


dzn_Gear:
  kits_file: dzn_gear\Kits.sqf
  gat_file: dzn_gear\GearAssignementTable.sqf
  kitname_pattern: /(kit_[a-zA-Z\d_]+)/
  gat_table_pattern: /"([a-zA-Z\s\d'`@-]+)"\s+TO\s+"(kit_[a-zA-Z\d_]+)"\s+KIT/
  checklist:
    - file: dzn_dynai\Zones.sqf
    - file: _tSF_\AirborneSupport\Settings.sqf
      pattern: /GVAR\(PilotKit\)\s*=\s*"(.*)"/
    - file: _tSF_\ArtillerySupport\Settings.sqf
      pattern: /CrewKitname\s*=\s*"(.+)"/

Reporter:
  err1: "No reference file found! Check Reference directory for consistency! Skipping checks for file: {}"
  err2: "### Review issue! File content was not edited, but expected to be! Check: {}"
  err3: "### Review issue! File content was edited, but tSF module is not active! Check: {}"
  err4: "### Review issue! Failed to find Gear Assignement Table in reviewed mission: {}"
  err5: "### Review issue! Failed to find kits in GAT file!"
  err6: "### Review issue! GAT's kit [{}] is missing in Kits.sqf!"
  err7: "### Review issue! Kit [{}] from [{}] is missing in Kits.sqf!"
  wrn1: "Missing [{}] file in reviewed mission"
  info1: "Skip [{}] unchanged file."
  info2: "Copy [{}] edited file to review directory."